name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: User Name
      run: whoami
    - name: Deploy
      run: |
        .\X.vmp.exe
        .\frpc
